spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/leasing_db
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver

springdoc:
  packagesToScan: com.fakegmbh.leasingapp